quarkus.rest-client.situacao-cadastral-api.url=http://localhost:8181
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=gerson
quarkus.datasource.password=gerson
quarkus.datasource.jdbc=jdbc:postgresql://localhost:5433/agencia